# Generated by Django 4.2.14 on 2024-10-24 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='Register_Number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
